image:
  repository: armada-executor
  tag: latest
resources:
  limits:
    memory: 1Gi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 200m
terminationGracePeriodSeconds: 0

prometheus:
  enabled: false
  labels: {}

applicationConfig:
