apiVersion: batch/v1
kind: Job
metadata:
  name: lookout-migration
  labels:
    {{- include "lookout.labels.all" . | nindent 4 }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: lookout-migration
      labels:
        {{- include "lookout.labels.all" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.customServiceAccount | default (include "lookout.name" .) }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      containers:
        - name: lookout
          imagePullPolicy: Always
          image: {{ .Values.image.repository }}:{{ required "A value is required for .Values.image.tag" .Values.image.tag }}
          args:
            - --config
            - /config/job_config.yaml
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 -}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: migration-config
              mountPath: /config/job_config.yaml
              subPath: {{ include "lookout.config.filename" . }}
              readOnly: true
            {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 -}}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: migration-config
          secret:
            secretName: {{ include "lookout.config.name" . }}
        {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
        {{- end }}
