version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout


  build:
    docker:
      - image: circleci/golang:1.12.6
        environment:
          GO111MODULE: "on"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: redis

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/G-Research/k8s-batch
    steps:
      - checkout
      - setup_remote_docker

      - aws-cli/install
      - aws-cli/configure
      
      # specify any bash command here prefixed with `run: `

      - run: go get -v -d ./...
      - run: go test -v ./...
      - run: exit $(gofmt -l . | wc -l)
      - run: docker build -t armada-executor:${CIRCLE_SHA1} -f ./build/executor/Dockerfile .

      - run:
          name: Push Image
          command: |
            source scripts/assume-role.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)
            docker tag armada-executor:${CIRCLE_SHA1} ${ECR_REPOSITORY}/armada-executor:${CIRCLE_SHA1}

