version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true    # default - false
    steps:
      - run:
          name: Pull image
          command: docker pull bsycorp/kind:v1.15.1

      - run:
          name: Install Kubectl
          command: |
            echo "Installing kubectl"
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Start Kubernetes
          command: |
            docker run -d --name kube --privileged -p 8443:8443 -p 10080:10080 bsycorp/kind:v1.15.1
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            echo "Kubernetes ready - run tests!"
            wget http://localhost:10080/config
            cp config ~/.kube/config
            kubectl get nodes