version: 2.1

commands:
  deploy-executor:
    parameters:
      worker-id:
        type: string
        default: "1"
    steps:
      - run:
          name: "Deploy to worker << parameters.worker-id >>"
          command: |
            echo $KUBECONFIG_WORKER_<< parameters.worker-id >> | base64 -d > kubeconfig_worker_<< parameters.worker-id >>_decoded.yaml
            export KUBECONFIG=./kubeconfig_worker_<< parameters.worker-id >>_decoded.yaml
            if timeout 15 helm list; then
              helm upgrade --install armada-executor --namespace=armada ./deployment/executor/ -f ./executor_config.yaml \
              --set applicationConfig.application.clusterId="worker-pool-<< parameters.worker-id >>" \
              --set image.repository=gresearchdev/armada-executor-dev  \
              --set image.tag="${CIRCLE_SHA1}"

              helm upgrade --install executor-cluster-monitoring --name executor-cluster-monitoring --namespace=common ./deployment/executor-cluster-monitoring --set interval=5s
            else
              echo Unable to connect to worker << parameters.worker-id >>
            fi

jobs:
  build:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    environment:
      GO111MODULE: "on"
      GOPATH: "/home/circleci/go"
      GOCACHE: "/home/circleci/go/cache"
    working_directory: ~/go/src/github.com/G-Research/armada
    steps:
      - checkout
      - run: e2e/setup/setup_environment.sh
      - run:
          name: Start cluster for e2e tests
          command: ./e2e/setup/setup_cluster_ci.sh

      - restore_cache:
          keys:
            - machine-go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Test
          command: make tests

      - run:
          name: Build & Run e2e tests
          command: make build-ci tests-e2e

      - run: cat go.sum

      - save_cache:
          key: machine-go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
            - "/home/circleci/go/cache"

      - run:
          name: ineffassign
          command: go run github.com/gordonklaus/ineffassign .

      - run:
          name: Check formatting
          command: |
            exit $(go run golang.org/x/tools/cmd/goimports -l -local "github.com/G-Research/armada" . | wc -l)


      - store_artifacts:
          path: bin/armadactl
          destination: armadactl

      - run:
          name: Push Image
          command: |

            if [ -z "${DOCKERHUB_USER}" ]
              then
                echo "Do not push image inside fork."
                exit 0
            fi

            TAG=${CIRCLE_SHA1}

            if [ ${CIRCLE_BRANCH} != master ]
              then
                TAG=branch-${CIRCLE_BRANCH}-${CIRCLE_SHA1}
            fi

            echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin

            docker tag armada gresearchdev/armada-server-dev:${TAG}
            docker push gresearchdev/armada-server-dev:${TAG}

            docker tag armada-executor gresearchdev/armada-executor-dev:${TAG}
            docker push gresearchdev/armada-executor-dev:${TAG}
  deploy:
    docker:
      - image: alpine/helm:2.13.1
    working_directory: /go/src/github.com/G-Research/armada
    steps:
      - checkout
      - run:
          name: "Extract config files from environment variables"
          command: |
            echo $ARMADA_CONFIG | base64 -d > armada_config.yaml
            echo $EXECUTOR_CONFIG | base64 -d > executor_config.yaml
      - run:
          name: "Deploy to services"
          command: |
            echo $KUBECONFIG_SERVICES | base64 -d > kubeconfig_services_decoded.yaml
            export KUBECONFIG=./kubeconfig_services_decoded.yaml
            if timeout 15 helm list; then
              helm upgrade --install armada --namespace=armada ./deployment/armada/ -f ./armada_config.yaml --set image.repository=gresearchdev/armada-server-dev --set image.tag="${CIRCLE_SHA1}"
            else
              echo Unable to connect to services cluster
            fi
      - deploy-executor:
          worker-id: "1"
      - deploy-executor:
          worker-id: "2"
      - deploy-executor:
          worker-id: "3"
      - deploy-executor:
          worker-id: "4"
      - deploy-executor:
          worker-id: "5"

  release:
    docker:
      - image: circleci/golang:1.12.6
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/G-Research/k8s-batch
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build armadactl release artifacts
          command: make build-armadactl-release RELEASE_VERSION=${CIRCLE_TAG}

      - store_artifacts:
          path: dist/*

      - run:
          name: Upload artifacts to Github release
          command: |
            for artifact in ./dist/*; do
              ./scripts/upload-github-release-asset.sh ${GITHUB_TOKEN} ${CIRCLE_TAG} $artifact
            done

            ./scripts/add-checksum-summary.sh ${GITHUB_TOKEN} ${CIRCLE_TAG}

      - run:
          name: Publish images
          command: |
            TAG=${CIRCLE_SHA1}
            RELEASE_TAG=${CIRCLE_TAG}

            echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin

            docker pull gresearchdev/armada-server-dev:${TAG}
            docker tag gresearchdev/armada-server-dev:${TAG} gresearchdev/armada-server:${RELEASE_TAG}
            docker push gresearchdev/armada-server:${RELEASE_TAG}

            docker pull gresearchdev/armada-executor-dev:${TAG}
            docker tag gresearchdev/armada-executor-dev:${TAG} gresearchdev/armada-executor:${RELEASE_TAG}
            docker push gresearchdev/armada-executor:${RELEASE_TAG}


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
