version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  basic:
    docker:
      - image: circleci/golang:1.12.6
    steps:
      - run: echo Hello
  e2e:
    machine:
      enabled: true
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Load relevant docker images
          command: |
            source scripts/assume-role.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)
            docker pull ${ECR_REPOSITORY}/armada:b91e651cba4ed065cbbbea5bf43ef688b40bd766
            docker pull ${ECR_REPOSITORY}/armada-executor:b91e651cba4ed065cbbbea5bf43ef688b40bd766
            docker images
      - run: test/end_to_end/setup/setup_environment.sh
      - run: test/end_to_end/setup/setup_clusters.sh
      - run: docker run -d --expose=6379 redis
      - run: docker run -d --expose=50051 ${ECR_REPOSITORY}/armada:b91e651cba4ed065cbbbea5bf43ef688b40bd766
      - run:
          name: Wait for cluster executors to be ready
          command: |
            export KUBECONFIG=$(kind get kubeconfig-path --name=cluster1)
            kubectl -n armada  wait --for=condition=available --timeout=60s deployment/executor

#      - run:
#          name: Run e2e tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - basic
      - hold:
          type: approval
          requires:
            - basic
      - e2e:
          requires:
            - hold