version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  e2e:
    machine:
      docker_layer_caching: true
    environment:
      GO111MODULE: "on"
      GOPATH: "/home/circleci/go"
      GOCACHE: "/home/circleci/go/cache"
    working_directory: ~/go/src/github.com/G-Research/k8s-batch
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Load relevant docker images
          command: |
            source scripts/assume-role.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)
            docker pull alpine:3.10
            docker pull ${ECR_REPOSITORY}/armada:cbb026d82f2776fd1423b19448dcac002242ce52
            docker pull ${ECR_REPOSITORY}/armada-executor:cbb026d82f2776fd1423b19448dcac002242ce52
            docker images
      - run: e2e/setup/setup_environment.sh
      - run:
          name: Alternative kind setup
          command: |
            docker run -d --name kube --privileged -p 8443:8443 -p 10080:10080 bsycorp/kind:v1.15.1
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            mkdir ~/.kube
            chmod 777 ~/.kube
            wget -P ~/.kube http://localhost:10080/config
            kubectl get nodes
      - run: docker run -d --expose=6379 --network=host redis
      - run: docker run -d --expose=50051 --network=host ${ECR_REPOSITORY}/armada:cbb026d82f2776fd1423b19448dcac002242ce52
      - run: docker run -d --network=host -v ~/.kube/config:/kube/config -e KUBECONFIG=/kube/config ${ECR_REPOSITORY}/armada-executor:cbb026d82f2776fd1423b19448dcac002242ce52
      - restore_cache:
          keys:
            - go-mod-speed-experiment-v10-{{ checksum "go.sum" }}
      - run:
          name: Build e2e test
          command: |
            go get -d ./...
      - run:
          name: Run e2e tests
          command: |
            INTEGRATION_ENABLED=true go test ./e2e/test/...
      - save_cache:
          key: go-mod-speed-experiment-v10-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
            - "/home/circleci/go/cache"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - e2e:
          filters:
            branches:
              ignore: master
