version: 2
jobs:
  build:
    machine: true
      docker_layer_caching: true
    steps:
      - run:
          name: Pull image
          command: docker pull bsycorp/kind:v1.15.1
      - run:
          name: Start Kubernetes
          command: |
            docker run -d --name kube --privileged -p 8443:8443 -p 10080:10080 bsycorp/kind:v1.15.1
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            echo "Kubernetes ready - run tests!"
