version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  e2e:
    machine:
      enabled: true
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Load relevant docker images
          command: |
            source scripts/assume-role.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)
            docker pull ${ECR_REPOSITORY}/armada:b91e651cba4ed065cbbbea5bf43ef688b40bd766
            docker images
      - run: test/end_to_end/setup/setup_environment.sh
#      - run:
#          name: Deploy executors to clusters
#      - run:
#          name: Run API
#      - run:
#          name: Run e2e tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - e2e