version: 2
jobs:
  e2e:
    machine:
      enabled: true
    steps:
      - run: test/end_to_end/setup/setup_environment.sh
#      - run:
#          name: Deploy executors to clusters
#      - run:
#          name: Run API
#      - run:
#          name: Run e2e tests

