version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.6
        environment:
          GO111MODULE: "on"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: redis

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/G-Research/k8s-batch
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: go get -v -d ./...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Test
          command: go test -v ./...

      - run:
          name: Check formatting
          command: exit $(gofmt -l . | wc -l)

      - run:
          name: Build
          command: make build

      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Push Image
          command: |
            source scripts/assume-role.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)

            docker tag armada-executor ${ECR_REPOSITORY}/armada:${CIRCLE_SHA1}
            docker push ${ECR_REPOSITORY}/armada:${CIRCLE_SHA1}

            docker tag armada-executor ${ECR_REPOSITORY}/armada-executor:${CIRCLE_SHA1}
            docker push ${ECR_REPOSITORY}/armada-executor:${CIRCLE_SHA1}
