image:
  repository: gresearchdev/armada-server
resources:
  limits:
    memory: 1Gi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 200m
additionalLabels: {}
terminationGracePeriodSeconds: 0
replicas: 1

prometheus:
  enabled: false
  labels: {}

applicationConfig:
  grpcPort: 50051
  httpPort: 8080
