image:
  repository: gresearchdev/armada-server
resources:
  limits:
    memory: 1Gi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 200m
additionalLabels: {}
terminationGracePeriodSeconds: 5
replicas: 1
strategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate
prometheus:
  enabled: false
  labels: {}
  serviceMonitor:
    interval: 10s
  prometheusRule:
    interval: 10s

applicationConfig:
  grpcPort: 50051
  httpPort: 8080
