image:
  repository: armada
  tag: latest
resources:
  limits:
    memory: 1Gi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 200m
terminationGracePeriodSeconds: 0
replicas: 1

prometheus:
  enabled: false
  labels: {}

applicationConfig:
  grpcPort: 50051
