application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 1s
  missingJobEventReconciliationInterval: 15s
  stuckPodScanInterval: 15s
  jobLeaseRenewalInterval: 15s
  podDeletionInterval: 5s
  allocateSpareClusterCapacityInterval: 5s
  podMetricsInterval: 1s
  queueUsageDataRefreshInterval: 5s
  UtilisationEventProcessingInterval: 1s
  UtilisationEventReportingInterval: 5m
apiConnection:
  armadaUrl : "localhost:50051"
metric:
  port: 9001
  exposeQueueUsageMetrics: false
kubernetes:
  impersonateUsers: false
  minimumPodAge: 3m
  failedPodExpiry: 10m
  stuckPodExpiry: 3m
