application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 1s
  missingJobEventReconciliationInterval: 15s
  stuckPodScanInterval: 15s
  jobLeaseRenewalInterval: 15s
  podDeletionInterval: 5s
  allocateSpareClusterCapacityInterval: 5s
  podMetricsInterval: 1s
  queueUsageDataRefreshInterval: 10s
apiConnection:
  armadaUrl : "localhost:50051"
metric:
  port: 9001
  exposeQueueUsageMetrics: true
kubernetes:
  impersonateUsers: false
  minimumPodAge: 3m
  failedPodExpiry: 10m
