application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 10s
  missingJobEventReconciliationInterval: 10s
  jobLeaseRenewalInterval: 10s
  allocateSpareClusterCapacityInterval: 10s
armada:
  url : "localhost:50051"
events:
  url : "localhost:50051"
