application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 1s
  missingJobEventReconciliationInterval: 15s
  stuckPodScanInterval: 15s
  jobLeaseRenewalInterval: 15s
  podDeletionInterval: 5s
  allocateSpareClusterCapacityInterval: 5s
  podMetricsInterval: 1s
apiConnection:
  armadaUrl : "localhost:50051"
metricsPort: 9001
kubernetes:
  impersonateUsers: false
