alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
  service:
    type: NodePort

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tlsProxy:
    enabled: false
  createCustomResource: false
