apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "executor.labels.identity" . | indent 6 }}
  template:
    metadata:
      name: {{ include "executor.name" . }}
      labels:
{{ include "executor.labels.all" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "executor.name" . }}
      containers:
        - name: executor
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ required "A value is required for .Values.image.tag" .Values.image.tag }}
          args:
            - --config
            - /config/application_config.yaml
            - --apiCredentialsPath
            - /config/api-credentials.yaml
            - --inCluster
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 9001
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: user-config
              mountPath: /config/application_config.yaml
              subPath: {{ include "executor.config.filename" . }}
            - name: api-credentials
              mountPath: /config/api-credentials.yaml
              subPath: {{ include "executor.api.credentials.filename" . }}
              readOnly: true
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      volumes:
        - name: user-config
          configMap:
            name: {{ include "executor.config.name" . }}
        - name: api-credentials
          secret:
            secretName: {{ include "executor.api.credentials.name" . }}
