apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "executor.labels.identity" . | indent 6 }}
  template:
    metadata:
      name: {{ include "executor.name" . }}
      labels:
{{ include "executor.labels.all" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "executor.name" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      containers:
        - name: executor
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ required "A value is required for .Values.image.tag" .Values.image.tag }}
          args:
            - --config
            - /config/application_config.yaml
{{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 9001
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: user-config
              mountPath: /config/application_config.yaml
              subPath: {{ include "executor.config.filename" . }}
              readOnly: true
{{- if .Values.additionalVolumeMounts }}
{{ toYaml .Values.additionalVolumeMounts | indent 12 }}
{{- end }}
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      volumes:
        - name: user-config
          secret:
            secretName: {{ include "executor.config.name" . }}
{{- if .Values.additionalVolumes }}
{{ toYaml .Values.additionalVolumes | indent 8 }}
{{- end }}

