apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "executor.labels.identity" . | indent 6 }}
  template:
    metadata:
      name: {{ include "executor.name" . }}
      labels:
{{ include "executor.labels.all" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.executor.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "executor.name" . }}
      containers:
        - name: executor
          imagePullPolicy: IfNotPresent
          image: {{ .Values.executor.image.repository }}:{{ required "A value is required for .Values.executor.image.tag" .Values.executor.image.tag }}
          args:
            - --config
            - /config/application_config.yaml
            - --inCluster
          resources:
{{ toYaml .Values.executor.resources | indent 12 }}
          volumeMounts:
            - name: user-config
              mountPath: /config/application_config.yaml
              subPath: {{ include "executor.application.config.filename" . }}
      volumes:
        - name: user-config
          configMap:
            name: {{ include "executor.config.name" . }}
