apiVersion: v1
kind: Service
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
spec:
  selector:
{{ include "executor.labels.identity" . | indent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: 9001
