{{ if not .Values.customServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "executor.labels.all" . | nindent 4 }}
{{ toYaml .Values.serviceAccount }}
{{ end }}