{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
{{- if .Values.prometheus.labels }}
{{ toYaml .Values.prometheus.labels | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
{{ include "executor.labels.identity" . | indent 6 }}
  endpoints:
    - port: metrics
      interval: 3s
{{- end }}
