image:
  repository: gresearchdev/armada-lookout-migration
  tag: LATEST
resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m
additionalLabels: {}
customServiceAccount: null
serviceAccount: null

migrationConfig: {}
