apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ required "A value is required for .Values.ingressClass" .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    certmanager.k8s.io/cluster-issuer: {{ required "A value is required for .Values.clusterIssuer" .Values.clusterIssuer }}
  labels:
    {{- include "armada.labels.all" . | nindent 4 }}
spec:
  rules:
  - host: {{ required "A value is required for .Values.hostname" .Values.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "armada.name" . }}
            servicePort: {{ .Values.applicationConfig.grpcPort }}
  tls:
    - hosts:
        - {{ required "A value is required for .Values.hostname" .Values.hostname }}
      secretName: armada-service-tls
