apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "armada.name" . }}-rest
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ required "A value is required for .Values.ingressClass" .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: {{ required "A value is required for .Values.clusterIssuer" .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    {{- include "armada.labels.all" . | nindent 4 }}
spec:
  rules:
  {{- $root := . -}}
  {{  range required "A value is required for .Values.hostnames" .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - path: /api(/|$)(.*)
          backend:
            serviceName: {{ include "armada.name" $root }}
            servicePort: {{ $root.Values.applicationConfig.httpPort }}
  {{ end }}
  tls:
    - hosts:
      {{- toYaml .Values.hostnames  | nindent 8 }}
      secretName: armada-service-tls
