apiVersion: v1
kind: Secret
metadata:
  name: {{ include "armada.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "armada.labels.all" . | indent 4 }}
type: Opaque
data:
  {{ include "armada.config.filename" . }}: |
{{- if .Values.applicationConfig }}
{{ toYaml .Values.applicationConfig | b64enc | indent 4 }}
{{- end }}
