
grpcPort: 50051
httpPort: 8080
metricsPort: 9000
priorityHalfTime: 20m
redis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000
eventsRedis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000
basicAuth:
  enableAuthentication: false
anonymousAuth: true
permissionGroupMapping:
  submit_jobs: ["everyone"]
  submit_any_jobs: ["everyone"]
  create_queue: ["everyone"]
  cancel_jobs: ["everyone"]
  cancel_any_jobs: ["everyone"]
  watch_all_events: ["everyone"]
  execute_jobs: ["everyone"]
scheduling:
  useProbabilisticSchedulingForAllResources: true
  queueLeaseBatchSize: 100
  minimumResourceToSchedule:
    memory: 100000000 # 100Mb
    cpu: 0.25
  maximalClusterFractionToSchedule: 0.25
eventRetention:
  expiryEnabled: true
  retentionDuration: 336h # Specified as a Go duration, values less than 0 (i.e -1) will result in infinite retention