
development: false
grpcPort: 50051
metricsPort: 9000
priorityHalfTime: 20m
redis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000
eventsRedis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000
basicAuth:
  enableAuthentication: false
permissionGroupMapping:
  submit_jobs: ["armada-admin"]
  create_queue: ["armada-admin"]
  cancel_jobs: ["armada-admin"]
  watch_all_events: ["armada-admin"]
  execute_jobs: ["executor"]

